version: '4.0'
services:
    db:
        container_name: ${CONTAINER_NAME}
        image: postgres
        restart: always
        ports:
            - '1021:5432'
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        volumes:
            - db_${CONTAINER_NAME}:/var/lib/postgresql/data
    pgadmin:
        container_name: pgadmin_${CONTAINER_NAME}
        image: dpage/pgadmin4
        restart: always
        ports:
            - '5050:80'
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
        volumes:
            - pgadmin_data_${CONTAINER_NAME}:/var/lib/pgadmin
        depends_on:
            - db
volumes:
    db_data_monorepo_bs:
    pgadmin_data_monorepo_bs:
